version: '3.8'
services:
  app:
    build:
      context: .
      target: production-main
      dockerfile: website/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - website/.env
    depends_on:
      - websocket
      - redis

  websocket:
    build:
      context: .
      target: production-websocket
      dockerfile: website/Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - website/.env

  sharp:
    build:
      context: .
      dockerfile: SHARP/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - SHARP/.env

  redis:
    image: redis:8-alpine
    volumes:
      - sharp_redisdata:/data
    command: "redis-server --save 60 1"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SHARP/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  pgdata:
  sharp_redisdata:
